### ISSUE TITLE
Remove pytest from package dependencies

### ISSUE THREAD

**Issue by vfdev-5** [longtermrisk/marltoolbox#1]
Hi @Manuscrit 

I think `pytest` can be removed from toolkit dependencies as it serves only for testing it:
https://github.com/longtermrisk/marltoolbox/blob/92e8f19f5588a10d61b6fade4808a5d67bfdf1ec/setup.py#L19

Let me know what do you think ?

**Comment by Manuscrit** [comment]
Sure you are right

**Comment by Manuscrit** [comment]
This is our first issue thanks! Don't hesitate to give us feedback this is greatly appreciated, I know that you have lot of experience on building research tools!

**Comment by vfdev-5** [comment]
Sure, let me reach out to you in private (via TDS slack) for other feedback I thinking of.
