### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by vfdev-5** [longtermrisk/marltoolbox#2]
It would be nice to see few badges in the README with
- CI status
- Docs
- Latest release version
- ...

As the README is very large, it could be helpful to add Table of Content and maybe the following:

<details>

<summary>
Description of something
</summary>

LARGE BLOCK OF CODE, TEXT etc

</details>

which is done as 
```
<details>

<summary>
Description of something
</summary>

LARGE BLOCK OF CODE, TEXT etc

</details>
```

A mention about how to contribute to this project is a sort of good practice in OSS. Then you could create few house keeping issues with label "help_wanted" or "good_first_issue"...

**Comment by Manuscrit** [comment]
I did a bunch of changes in that direction
Thanks that really helps!

**Comment by vfdev-5** [comment]
TODO list you can put to a Roadmap file or page in Wiki. If you use Wiki make sure to have it editable only by maintainers.
